version: '3'

services:
  web:
    build: .
    ports:
      - '3000:3000' # Maps host:container port
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next