version: '3.8'

services:
  app-BrainKBUIManager-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ENVIRONMENT=production
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge